# Generated by Django 5.1.7 on 2025-04-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartroom', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='avater.png', null=True, upload_to=''),
        ),
    ]
